# fly.toml app configuration file generated for testara
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "testara-app" # IMPORTANT: You will need to change this to your unique app name
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  DB_PATH = "/data/testara.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[mounts]]
  source = "testara_data"
  destination = "/data"
  processes = ["app"]
